#!/usr/bin/env bash
NUM=07
CLASS=788
NAME="hw${NUM}-${CLASS}"
PDFDIR=../pdf/
FILE="$NAME.tex"

texi2pdf $FILE

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
