#!/usr/bin/env bash
NAME="cover.letter"
PDFDIR=../pdf/

texi2pdf $NAME.tex

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
