#!/usr/bin/env bash
NAME="main"
PDFDIR=../pdf/
FILE="${NAME}.tex"

#texi2pdf $FILE
latex ${NAME} && biber ${NAME} && pdflatex ${NAME}

if [ ! -d ../pdf ]; then
   mkdir ../pdf
fi

mv ${NAME}.pdf ../pdf/dissertation.pdf

./clean
