#!/usr/bin/env bash
NAME="undergrad.research"
PDFDIR=../pdf/
FILE="${NAME}.tex"
#texi2pdf ${FILE}
latexmk -pdf ${FILE}

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv ${NAME}.pdf ../pdf

#rm -fr *.log
#rm -fr *.aux
#rm -fr *.blg
latexmk -C
rm -fr *.bbl
rm -fr *~
