#!/usr/bin/env bash
NAME="hom.alg-10.4"
PDFDIR=../pdf/
FILE="${NAME}.tex"

texi2pdf $FILE

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *.out
rm -fr *~
