#!/usr/bin/env perl
use strict;
use warnings;

use lib '/Users/blake/hacking/perl/modules/';
use ptex;

#Preamble
my $documentClass = "amsart";
my @docClassArgs = ("10pt");
my @texPackages = ("graphicx","enumerate", "amsmath", "amsthm","amssymb");

#Cover Page info.
my ($num,
    $course) = (6, 
		"Math-251");

#Title page
my $school = "University of Vermont";
my ($author,
    $date,
    $title) = ("Blake Farman", 
	       "Friday, October 22, 2010",
	       "$course: Homework $num\\\\\n");

my $p = {
    "docClass" => $documentClass,
    "docArgs" => \@docClassArgs,
    "pkgs" => \@texPackages,
    "title" => $title,
    "author" => $author,
    "date" => $date,
    "isCP" => 0,
    "other" => "\\openup 5pt" 
};


print ptex::preamble($p);

my $Z = "\\mathbb{Z}";
my $R = "\\mathbb{R}";

my ($beq,$eeq) = ("\\begin{eqnarray*}\n", "\\end{eqnarray*}\n");

my $name = "1"; 
my $thm = "a) Prove that in the quotient group \\(G/N\\), \\((gN)^{\\alpha} = g^{\\alpha}N\\) for all \\(\\alpha \\in $Z\\)\n\n" . 
    "b) Use the preceeding exercise to prove that the order of the element \\(gN\\) in \\(G/N\\) is \\(n\\), where \\(n\\) is the smallest positive integer such that \\(g^n \\in N\\) (and \\(gN\\) has infinite order if no such positive integer exists).  Give an example to show that the order of \\(gN\\) is \\(G/N\\) may be strictly smaller than the order of \\(g\\) in \\(G\\).\n"; 
my $pf = "a) Let \\(\\alpha \\in $Z\\) be given and observe that \\(g^{-1}NgN = gNg^{-1}N = N\\), which is the identity in \\(G/N\\), implies \\((gN)^{-1} = g^{-1}N\\).\n" . 
    "Then" . 
    $beq .
    ptex::printEqnArray([["(gN)^{\\alpha}", "(gN)^{".ptex::frac("\\alpha", "|\\alpha|")."}\\cdot(gN)^{" . ptex::frac("\\alpha", "|\\alpha|") ."} \\cdot \\ldots \\cdot(gN)^{" . ptex::frac("\\alpha", "|\\alpha|") . "}"],
			 ["", "g^{" . ptex::frac("\\alpha", "|\\alpha|") . "}N \\cdot g^{" . ptex::frac("\\alpha", "|\\alpha|") . "}N \\cdot \\ldots \\cdot g^{" . ptex::frac("\\alpha", "|\\alpha|") . "}N"],
			 ["", "g^{\\alpha}N,"]] , "=") . 
    $eeq .
    "which holds for \\(\\alpha < 0\\) by the result of Exercise 20 from section 1.1 (Homework 1).\n\n" . 
    "b)  Let \\(n\\) be the smallest positive integer such that \\(g^{n} \\in N\\), with \\(n = \\infty\\) if no such \\(n\\) exists.\n" . 
    "By the result from part (a), \\((gN)^n = g^nN\\), so it follows from Proposition 4 that  \\(g^nN = N\\)  if and only if \\(g^n \\in N\\).\n" . 
    "Since \\(n\\) was assumed to be the smallest such \\(n\\) for which \\(g^n \\in N\\), it follows that \\(n\\) is the order of \\(gN\\) in \\(G/N\\).";

print ptex::thm($name, $name, $thm . ptex::pf($pf));

$name = "2"; 
$thm = "Prove that if \\(H\\) and \\(K\\) are normal subgroups of a group \\(G\\), then their intersection \\(H \\cap K\\) is also a normal subgroup of \\(G\\).\n"; 
$pf = "By the result of Exercise 6, Homework 3, \\(H \\cap K\\) is a subgroup of \\(G\\).\n" . 
    "So it remains only to show that \\(H \\cap K\\) is normal.\n" . 
    "To that end, let \\(h\\) be an arbitrary element of \\(H \\cap K\\) and observe that for every element \\(g\\) of \\(G\\), \\(ghg^{-1} \\in H\\) and \\(ghg^{-1} \\in K\\).\n" . 
    "So it follows that \\(g(H \\cap K)g^{-1} \\subseteq H \\cap K\\) for all \\(g \\in G\\).\n" . 
    "Therefore, by Theorem 6, \\(H \\cap K\\) is normal.\n";

print ptex::thm($name, $name, $thm . ptex::pf($pf));

$name = "3"; 
$thm = "Prove that if \\(N \\trianglelefteq G\\) and \\(H\\) is any subgroup of \\(G\\), then \\(N \\cap H \\trianglelefteq H.\\)\n"; 
$pf = "As in the previous exercise, \\(N \\cap H\\) is a subgroup of \\(G\\).\n" . 
    "Moreover, \\(N \\cap H \\subseteq H\\) implies \\(N \\cap H\\) is a subgroup of \\(H\\).\n" . 
    "So, as before, it remains only to show that \\(N \\cap H\\) is normal.\n" . 
    "Let \\(g\\) and \\(h\\) be arbitrary elements of \\(N \\cap H\\) and \\(H\\), respectively.\n" . 
    "Then observe that \\(hgh^{-1} \\in N\\) since \\(N \\trianglelefteq G\\), and \\(hgh^{-1} \\in H\\) since \\(H \\leq G\\).\n" . 
    "Hence \\(h(N \\cap H)h^{-1} \\subseteq N \\cap H\\).\n" . 
    "Therefore, by Theorem 6, \\(H \\cap K\\) is normal, as desired.\n";

print ptex::thm($name, $name, $thm . ptex::pf($pf));

my $sigma = "\\sigma";
my $tau = "\\tau";
my $sbar = "\\overline{$sigma}";
my $tbar = "\\overline{$tau}";

$name = "4"; 
$thm = "Let \\(G\\) be the quasidihedral group of order 16:\n" . 
    "\\[G = \\left<\\sigma, \\tau \\mid \\sigma^8 = \\tau^2 = 1, \\quad \\sigma\\tau = \\tau\\sigma^3\\right>\\]" . 
    "and let \\(\\overline{G} = G/\\left<\\sigma^4\\right>\\) be the quotient of \\(G\\) by the subgroup generated by \\(\\sigma^4\\) (this subgroup is the center of \\(G\\), hence is normal).\n\n" . 
    "a) Show that the order of \\(\\overline{G}\\) is 8.\n\n" . 
    "b) Exhibit each element of \\(\\overline{G}\\) in the form \\(\\overline{\\tau}^a\\overline{\\sigma}^b\\), for some integers \\(a\\) and \\(b\\).\n\n" .
    "c) Find the order of each of the elements of \\(\\overline{G}\\) exhibited in (b).\n\n" . 
    "d) Write each of the following elements of \\(\\overline{G}\\) in the form in the form \\(\\overline{\\tau}^a\\overline{\\sigma}^b\\),\n" . 
    "for some integers \\(a\\) and \\(b\\) as in (b): \\(\\quad \\overline{\\sigma\\tau}, \\quad \\overline{\\tau\\sigma^{-2}\\tau}, \\quad \\overline{\\tau^{-1}\\sigma^{-1}\\tau\\sigma}\\)\n\n" . 
    "e) Prove that \\(\\overline{G} \\cong D_8.\\)"; 
$pf = "a) First observe that \\(\\left<\\sigma^4\\right> = \\{1,\\sigma^4\\}\\), so each element of \\(\\overline{G}\\) has two representatives.\n" . 
    "Since \\(QD_{16}\\) has 16 elements, the group \\(QD_{16}/\\left<\\sigma^4\\right>\\) will have the 8 elements, enumerated below.\n\n". 
    "b)Note that the left and right cosets are equivalent since \\(\\left<\\sigma^4\\right> = Z(G)\\).\n\n" . 
    ptex::math(
	"\\begin{array}{ll}\n" . 
	ptex::printArray([["\\overline{1} = $sbar^4 = \\{1, $sigma^4\\}", "$tbar = $tbar$sbar^4 = \\{$tau, $tau$sigma^4\\}"],
			  ["$sbar = $sbar^5 = \\{$sigma, $sigma^5\\}", "$tbar$sbar = $tbar$sbar^5 = \\{$tau$sigma, $tau$sigma^5\\}"],
			  ["$sbar^2 = $sbar^6 = \\{$sigma^2, $sigma^6\\}", " $tbar$sbar^2 = $tbar$sbar^6 = \\{$tau$sigma^2, $tau$sigma^6\\}"],
			  ["$sbar^3 = $sbar^7 = \\{$sigma^3, $sigma^7\\}", "$tbar$sbar^3 = $tbar$sbar^7 = \\{$tau$sigma^3, $tau$sigma^7\\}"]]) .
	"\\end{array}") . 
    "\n\n" . 
    "c) The order of each of the elements above is given below.\n" . 
    ptex::math(
	"\\begin{array}{ll}\n" . 
	ptex::printArray([["|\\overline{1}| = 1", "|$tbar| = 2"],
			  ["|$sbar| = 4", "|$tbar$sbar| = 2"],
			  ["|$sbar^2| = 2", "|$tbar$sbar^2| = 2"],
			  ["|$sbar^3| = 4", "|$tbar$sbar^3| = 2"]]) .
	"\\end{array}") .
    "\n\n" . 
    "d) \\(\\overline{$sigma$tau} = $tbar$sbar^3\\), \\(\\overline{$tau$sigma^{-2}$tau} = $sbar^2\\) , \\(\\overline{$tau^{-1}$sigma^{-1}$tau$sigma} = $sbar^6.\\)\n\n" . 
    "e)Define a bijective map" . 
    "\\[\\varphi: \\overline{G} \\rightarrow D_8\\]\n" .
    "\\[$tbar^a$sbar^b \\mapsto s^ar^b.\\]\n" . 
    "To see that \\(\\varphi\\) is a homormorphism, take two elements of \\(\\overline{G}\\), \\($tbar^a$sbar^b,$tbar^c$sbar^d\\).  Then\n" .
    $beq .
    ptex::printEqnArray([["\\varphi($tbar^a$sbar^b$tbar^c$sbar^d)", "\\varphi($tbar^{a+c}$sbar^{3b+d})"],
			 ["", "s^{a+c}r^{3b+d}"],
			 ["", "s^ar^{-3b}s^cr^d"],
			 ["", "s^ar^{9b}s^cr^d"],
			 ["", "s^ar^bs^cr^d"],
			 ["", "\\varphi($tbar^a$sbar^b)\\varphi($tbar^c$sbar^d)."]] , "=") . 
    $eeq . "\n" . 
    "Therefore, \\(\\overline{G} \\cong D_8\\).\n";    
print ptex::thm($name, $name, $thm . ptex::pf($pf));

$name = "5"; 
$thm = "Let \\(G\\) be the modular group of order 16:\n" . 
    "\\[G = \\left<u,v \\mid u^2 = v^8 = 1, \\quad vu = uv^5\\right>\\]" . 
    "and let \\(\\overline{G} = G/\\left<v^4\\right>\\) be the quotient of \\(G\\) by the subgroup generated by \\(v^4\\) (this subgroup is contained in the center of \\(G\\), hence is normal).\n\n" . 
    "a) Show that the order of \\(\\overline{G}\\) is 8.\n\n" . 
    "b) Exhibit each element of \\(\\overline{G}\\) in the form \\(\\overline{u}^a\\overline{v}^b\\), for some integers \\(a\\) and \\(b\\).\n\n" . 
    "c) Find the order of each of the elements of \\(\\overline{G}\\) exhibited in (b).\n\n" . 
    "d) Write each of the following elements of \\(\\overline{G}\\) in the form \\(\\overline{u}^a\\overline{v}^b\\), for some integers \\(a\\) and \\(b\\) as in (b): \\(\\quad \\overline{vu}, \\quad \\overline{uv^{-2}u}, \\quad \\overline{u^{-1}v^{-1}uv}\\).\n\n" . 
    "e) Prove that \\(\\overline{G}\\) is abelian and is isomorphic to \\(Z_2 \\times Z_4\\)."; 
$pf = "a) Since \\(\\left< v^4 \\right> = \\{1,v^4\\}\\) each element of \\(\\overline{G}\\) has two representatives.\n" . 
    "Since \\(G\\) has 16 elements, the group \\(\\overline{G}\\) will have the 8 elements, enumerated below.\n\n" . 
    "b)" . 
    ptex::math(
	"\\begin{array}{ll}\n" . 
	ptex::printArray([["\\overline{1} = \\overline{v}^4 = \\{1, \\overline{v}^4\\}", "\\overline{u} = \\overline{u}\\overline{v}^4 = \\{\\overline{u}, \\overline{u}\\overline{v}^4\\}"],
			  ["\\overline{v} = \\overline{v}^5 = \\{\\overline{v}, \\overline{v}^5\\}", "\\overline{u}\\overline{v} = \\overline{u}\\overline{v}^5 = \\{\\overline{u}\\overline{v}, \\overline{u}\\overline{v}^5\\}"],
			  ["\\overline{v}^2 = \\overline{v}^6 = \\{\\overline{v}^2, \\overline{v}^6\\}", " \\overline{u}\\overline{v}^2 = \\overline{u}\\overline{v}^6 = \\{\\overline{u}\\overline{v}^2, \\overline{u}\\overline{v}^6\\}"],
			  ["\\overline{v}^3 = \\overline{v}^7 = \\{\\overline{v}^3, \\overline{v}^7\\}", "\\overline{u}\\overline{v}^3 = \\overline{u}\\overline{v}^7 = \\{\\overline{u}\\overline{v}^3, \\overline{u}\\overline{v}^7\\}"]]) .
	"\\end{array}") . 
    "\n\n" . 
    "c) The order of each of the elements above is given below.\n" . 
    ptex::math(
	"\\begin{array}{ll}\n" . 
	ptex::printArray([["|\\overline{1}| = 1", "|\\overline{u}| = 2"],
			  ["|\\overline{v}| = 4", "|\\overline{u}\\overline{v}| = 4"],
			  ["|\\overline{v}^2| = 2", "|\\overline{u}\\overline{v}^2| = 2"],
			  ["|\\overline{v}^3| = 4", "|\\overline{u}\\overline{v}^3| = 4"]]) .
	"\\end{array}") .
    "\n\n" . 
    "d) \\(\\overline{vu} = \\overline{u}\\overline{v}^5\\), \\(\\overline{uv^{-2}u} = \\overline{v}^6\\) , \\(\\overline{u^{-1}v^{-1}uv} = \\overline{v}^3.\\)\n\n" . 
    "e)Define a bijective map" . 
    "\\[\\varphi: \\overline{G} \\rightarrow Z_2 \\times Z_4\\]\n" .
    "\\[\\overline{u}^a\\overline{v}^b \\mapsto (x^a,y^b).\\]\n" . 
    "To see that \\(\\varphi\\) is a homormorphism, take two elements of \\(\\overline{G}\\), \\(\\overline{u}^a\\overline{v}^b,\\overline{u}^c\\overline{v}^d\\).  Then\n" .
    $beq .
    ptex::printEqnArray([["\\varphi(\\overline{u}^a\\overline{v}^b\\overline{u}^c\\overline{v}^d)", "\\varphi(\\overline{u}^{a+c}\\overline{v}^{5b+d})"],
			 ["", "(x^ax^c,y^by^d)"],
			 ["", "(x^a,y^b)(x^c,y^d)"],
			 ["", "\\varphi(\\overline{u}^a\\overline{v}^b)\\varphi(\\overline{u}^c\\overline{v}^d)."]] , "=") . 
    $eeq . "\n" . 
    "Therefore, \\(\\overline{G} \\cong Z_2 \\times Z_4\\).\n"; ;

print ptex::thm($name, $name, $thm . ptex::pf($pf));

$name = "6"; 
$thm = "Prove that if \\(G/Z(G)\\) is cyclic, then \\(G\\) is abelian.\n"; 
$pf = "Assume \\(G/Z(G)\\) is cyclic and let \\(xZ(G)\\) generate \\(G/Z(G)\\).\n" . 
    "Let \\(g_1,g_2\\) be elements of \\(G\\).\n". 
    "Then for some positive integers \\(a,b\\), \\(g_1Z(G) = x^aZ(G)\\) and \\(g_2Z(G) = x^bZ(G)\\).\n" . 
    "Hence by Proposition 4 \\(g_1x^{-a},g_2x^{-b} \\in Z(G)\\).\n" . 
    "Therefore\n" . 
    $beq .
    ptex::printEqnArray([["g_1g_2", "x^a(g_1x^{-a})x^b(g_2x^{-b})"],
			 ["", "x^ax^b(g_2x^{-b})(g_1x^{-a})"],
			 ["", "x^bx^a(g_2x^{-b})(g_1x^{-a})"],
			 ["", "x^b(g_2x^{-b})x^a(g_1x^{-a})"],
			 ["", "g_2g_1,"]] , "=") . 
    $eeq . 
    "implies \\(G\\) is abelian, as desired.\n";

print ptex::thm($name, $name, $thm . ptex::pf($pf));

$name = "7"; 
$thm = "Assume both \\(H\\) and \\(K\\) are normal subgroups of \\(G\\) with \\(H \\cap K = 1\\).  Prove that \\(xy = yx\\) for all \\(x \\in H\\) and \\(y \\in K\\).\n"; 
$pf = "Let \\(h\\) and \\(k\\) be elements of \\(H\\) and \\(K\\), respectively.\n" . 
    "Consider \\(hkh^{-1}k^{-1}\\) and observe that \\(hkh^{-1} \\in K\\) and \\(kh^{-1}k^{-1} \\in H\\), since \\(H\\) and \\(K\\) are normal subgroups of \\(G\\).\n" . 
    "Hence \\(h(kh^{-1}k^{-1}) \\in H\\) and \\((hkh^{-1})k^{-1} \\in K\\), from which it follows that \\[h(kh^{-1}k^{-1}) = (hkh^{-1})k^{-1} \\in H \\cap K.\\]\n" . 
    "Therefore \\(hkh^{-1}k^{-1} = 1\\) implies \\(hk = kh\\), as desired.";

print ptex::thm($name, $name, $thm . ptex::pf($pf));
#print "\\bibliographystyle{plain}" .
#    "\\bibliography{refs}";
print ptex::endDoc();
